version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: wincloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wincloud_prod}
      POSTGRES_DB: wincloud
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wincloud_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wincloud -d wincloud"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache & Session Store
  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-wincloud_redis}
    volumes:
      - redis_data:/data
    networks:
      - wincloud_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-wincloud_redis}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Backend API (Production)
  backend:
    build:
      context: ./backend
      target: production
    restart: always
    environment:
      # Database
      DATABASE_URL: postgresql://wincloud:${POSTGRES_PASSWORD:-wincloud_prod}@db:5432/wincloud

      # Redis
      REDIS_URL: redis://:${REDIS_PASSWORD:-wincloud_redis}@redis:6379/0

      # Application
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "false"
      ENVIRONMENT: production

      # CORS
      CORS_ORIGINS: '["https://wincloud.app","https://panel.wincloud.app","https://api.wincloud.app"]'

      # DigitalOcean
      DO_SSH_KEY_ID: ${DO_SSH_KEY_ID:-}

      # Domains for production
      API_DOMAIN: api.wincloud.app
      PANEL_DOMAIN: panel.wincloud.app

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/tokens_secure.json:/app/tokens_secure.json:ro
    networks:
      - wincloud_network

  # Frontend Production Build
  frontend:
    build:
      context: ./frontend
      target: production
      args:
        REACT_APP_API_URL: https://api.wincloud.app
        REACT_APP_ENVIRONMENT: production
    restart: always
    depends_on:
      - backend
    networks:
      - wincloud_network

  # Home/Landing Page Production
  home:
    build: 
      context: ./home
      target: production
    restart: always
    environment:
      - NODE_ENV=production
      - VUE_APP_API_URL=https://api.wincloud.app
    networks:
      - wincloud_network

  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/ssl/certs/wincloud.app.pem:/etc/nginx/ssl/wincloud.app.pem:ro
      - /etc/ssl/private/wincloud.app.key:/etc/nginx/ssl/wincloud.app.key:ro
      - nginx_cache:/var/cache/nginx
      - nginx_logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
      - home
    networks:
      - wincloud_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  nginx_cache:
    driver: local
  nginx_logs:
    driver: local

networks:
  wincloud_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
