version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: wincloud
      POSTGRES_PASSWORD: wincloud_dev
      POSTGRES_DB: wincloud_dev
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C.UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - wincloud_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wincloud -d wincloud_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis Cache & Session Store
  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --appendonly yes --requirepass wincloud_dev_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - wincloud_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "wincloud_dev_redis", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      target: development
    restart: always
    ports:
      - "5000:5000"
    environment:
      # Database
      DATABASE_URL: postgresql://wincloud:wincloud_dev@db:5432/wincloud_dev

      # Redis
      REDIS_URL: redis://:wincloud_dev_redis@redis:6379/0

      # Application
      SECRET_KEY: dev-secret-key-change-in-production
      DEBUG: "true"
      ENVIRONMENT: development

      # CORS
      CORS_ORIGINS: '["http://localhost:3000","http://localhost:5173","http://localhost:7001","http://127.0.0.1:5173","http://127.0.0.1:7001"]'

      # DigitalOcean
      DO_SSH_KEY_ID: ${DO_SSH_KEY_ID:-}

      # Domains for development
      API_DOMAIN: localhost:5000
      PANEL_DOMAIN: localhost:5173

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./backend/tokens_secure.json:/app/tokens_secure.json:ro
    networks:
      - wincloud_network
    command: python run_minimal_real_api.py

  # Frontend Development Server (React + Vite)
  frontend:
    build:
      context: ./frontend
      target: development
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_ENVIRONMENT=development
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - wincloud_network

  # Home/Landing Page (Vue.js)
  home:
    build:
      context: ./home
      target: development
    restart: always
    ports:
      - "7001:7000"
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://localhost:5000
    volumes:
      - ./home:/app
      - /app/node_modules
    networks:
      - wincloud_network
    command: npm run dev

  # Database Admin (Adminer)
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_NAME: wincloud_dev
    depends_on:
      - db
    networks:
      - wincloud_network

  # Redis Admin (Redis Commander)
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379:0:wincloud_dev_redis
      HTTP_USER: admin
      HTTP_PASSWORD: wincloud_redis_ui
    depends_on:
      - redis
    networks:
      - wincloud_network

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  wincloud_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
