"""Add BuildProgress model

Revision ID: b45aa30d7839
Revises: d4fb29bab97e
Create Date: 2025-07-26 23:15:09.173174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45aa30d7839'
down_revision: Union[str, None] = 'd4fb29bab97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('droplet_id', sa.String(length=36), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['droplet_id'], ['droplets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('build_progress')
    # ### end Alembic commands ###
